### ISSUE TITLE
Provide helpful message instead of crashing, when a symbol cannot be resolved.

### ISSUE THREAD

**Issue by kbauer** [lyz-code/autoimport#131]
## Description

Currently, when `autoimport FILENAME.py` does not find a suitable
completion, the program just crashes.

Instead in such as case, that symbol should be skipped and informative
messages should be given.

## Desirable behavior

Consider this exmaple file:

    ## -- demo.py
    def f(x):
        return sin(x) + cos(x)

Instead, it would be desirable to obtain an output message along the lines of

    >>> autoimport demo.py
    demo.py:2: No such module: 'cos'
    demo.py:2: No such module: 'sin'

and otherwise have `autoimport` continue its work.

## Actual behavior

For such a file, `autoimport demo.py` crashes:

    >>> autoimport demo.py 2>&1 | head -5
    Traceback (most recent call last):
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 736, in __str__
        return self._str
    AttributeError: _str
    

## Interaction with explicit imports

The current behavior of `autoimport` allows to import objects from
modules by explicitly specifying them, e.g.

    ## -- demo2.py
    def f(x):
        return sin(x) + cos(x)
        from numpy import sin, cos

which allows for more convenient workflows than contantly jumping back
to the import statements by using `autoimport`'s "move imports to
top" functionality.

    >>> autoimport demo2.py && cat demo2.py
    from numpy import sin, cos
    
    def f(x):
        return sin(x) + cos(x)

However, it fails if any of the missing imports are not given
explicitly, e.g.

    ## -- demo3.py
    def f(x):
        return sin(x) + cos(x)
        from numpy import sin

    >>> autoimport demo3.py 2>&1 | tail -5
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 738, in __str__
        self._str = self._format_parsed_parts(self._drv, self._root,
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 718, in _format_parsed_parts
        return drv + root + cls._flavour.join(parts[1:])
    RecursionError: maximum recursion depth exceeded while calling a Python object

## -- demo.py
    def f(x):
        return sin(x) + cos(x)

    >>> autoimport demo.py
    Traceback (most recent call last):
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 736, in __str__
        return self._str
    AttributeError: _str
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/USERNAME/anaconda3/bin/autoimport", line 8, in <module>
        sys.exit(cli())
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
        return self.main(*args, **kwargs)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/click/core.py", line 1062, in main
        rv = self.invoke(ctx)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/click/core.py", line 763, in invoke
        return __callback(*args, **kwargs)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/autoimport/entrypoints/cli.py", line 19, in cli
        fixed_code = services.fix_files(files)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/autoimport/services.py", line 27, in fix_files
        fixed_source = fix_code(source)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/autoimport/services.py", line 67, in fix_code
        return SourceCode(original_source_code).fix()
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/autoimport/model.py", line 59, in fix
        self._fix_flake_import_errors()
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/autoimport/model.py", line 248, in _fix_flake_import_errors
        self._add_package(object_name)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/autoimport/model.py", line 260, in _add_package
        import_string = self._find_package(object_name)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/autoimport/model.py", line 287, in _find_package
        package = getattr(self, check)(name)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/autoimport/model.py", line 303, in _find_package_in_our_project
        project_package = os.path.basename(here()).replace("-", "_")
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/pyprojroot/pyprojroot.py", line 44, in here
        project_path = py_project_root(Path(".").cwd(), project_files)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/pyprojroot/pyprojroot.py", line 18, in py_project_root
        return py_project_root(path.parent, project_files)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/pyprojroot/pyprojroot.py", line 18, in py_project_root
        return py_project_root(path.parent, project_files)
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/pyprojroot/pyprojroot.py", line 18, in py_project_root
        return py_project_root(path.parent, project_files)
      [Previous line repeated 971 more times]
      File "/home/USERNAME/anaconda3/lib/python3.9/site-packages/pyprojroot/pyprojroot.py", line 15, in py_project_root
        found = list(path.glob(file))
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 1167, in glob
        for p in selector.select_from(self):
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 533, in _select_from
        if (is_dir if self.dironly else exists)(path):
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 1414, in exists
        self.stat()
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 1222, in stat
        return self._accessor.stat(self)
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 743, in __fspath__
        return str(self)
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 738, in __str__
        self._str = self._format_parsed_parts(self._drv, self._root,
      File "/home/USERNAME/anaconda3/lib/python3.9/pathlib.py", line 718, in _format_parsed_parts
        return drv + root + cls._flavour.join(parts[1:])
    RecursionError: maximum recursion depth exceeded while calling a Python object

## Version info

    >>> python -c "import autoimport.version; print(autoimport.version.version_info())"
               autoimport version: 0.7.1
                   python version: 3.9.5 (default, May 18 2021, 19:34:48)  [GCC 7.3.0]
                         platform: Linux-4.12.14-lp151.28.91-default-x86_64-with-glibc2.26

`autoimport` was installed by:

    >>> pip3 install git+https://github.com/lyz-code/autoimport.git@master
    Collecting git+https://github.com/lyz-code/autoimport.git@master
      Cloning https://github.com/lyz-code/autoimport.git (to revision master) to ./pip-req-build-q12jz4nv
      Running command git clone -q https://github.com/lyz-code/autoimport.git /tmp/pip-req-build-q12jz4nv
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'done'
    Requirement already satisfied: Click in /home/USERNAME/anaconda3/lib/python3.9/site-packages (from autoimport==0.7.1) (8.0.1)
    Requirement already satisfied: autoflake in /home/USERNAME/anaconda3/lib/python3.9/site-packages (from autoimport==0.7.1) (1.4)
    Requirement already satisfied: sh in /home/USERNAME/anaconda3/lib/python3.9/site-packages (from autoimport==0.7.1) (1.14.2)
    Requirement already satisfied: pyprojroot in /home/USERNAME/anaconda3/lib/python3.9/site-packages (from autoimport==0.7.1) (0.2.0)
    Requirement already satisfied: pyflakes>=1.1.0 in /home/USERNAME/anaconda3/lib/python3.9/site-packages (from autoflake->autoimport==0.7.1) (2.2.0)

**Comment by kbauer** [comment]
For reproducing:

[crash.bash.txt](https://github.com/lyz-code/autoimport/files/7021181/crash.bash.txt)

**Comment by lyz-code** [comment]
Hi @kbauer, I'm glad you're thoroughly testing the tool and taking the time for opening the issues.

I've fixed it in 0.7.2, with #131 please check if you can no longer reproduce the bug.

**Comment by kbauer** [comment]
I can confirm that with 0.7.2 no crash occurs anymore.
