### ISSUE TITLE
crashes on empty file

### ISSUE THREAD

**Issue by Jasha10** [lyz-code/autoimport#133]
Hello,

Autoimport crashes on an empty file.
Here is a minimal example:
```text
$ touch empty.py
$ autoimport empty.py
Traceback (most recent call last):
  File "/home/jasha10/miniconda3/envs/pysc/bin/autoimport", line 8, in <module>
    sys.exit(cli())
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/entrypoints/cli.py", line 19, in cli
    fixed_code = services.fix_files(files)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/services.py", line 27, in fix_files
    fixed_source = fix_code(source)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/services.py", line 67, in fix_code
    return SourceCode(original_source_code).fix()
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/model.py", line 47, in __init__
    self._split_code(source_code)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/model.py", line 78, in _split_code
    self._extract_typing_statements(source_code_lines)
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/autoimport/model.py", line 154, in _extract_typing_statements
    if re.match(r"^if TYPE_CHECKING:$", source_lines[typing_start_line]):
IndexError: list index out of range
```

Autoimport version 0.7.2
CPython version 3.9.6

**Comment by lyz-code** [comment]
Hi @Jasha10, thanks for taking the time to open the bug. I've fixed it in #138 and released under 0.7.3

If the bug remains, please reopen the issue
