### ISSUE TITLE
Mac arm64 issues

### ISSUE THREAD

**Issue by yoland68** [lyz-code/autoimport#247]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/yoland/Library/Python/3.10/lib/python/site-packages/autoimport/__main__.py", line 3, in <module>
    from autoimport.entrypoints.cli import cli
  File "/Users/yoland/Library/Python/3.10/lib/python/site-packages/autoimport/entrypoints/cli.py", line 10, in <module>
    from maison.config import ProjectConfig
  File "/Users/yoland/Library/Python/3.10/lib/python/site-packages/maison/__init__.py", line 2, in <module>
    from .config import ProjectConfig
  File "/Users/yoland/Library/Python/3.10/lib/python/site-packages/maison/config.py", line 12, in <module>
    from maison.schema import ConfigSchema
  File "/Users/yoland/Library/Python/3.10/lib/python/site-packages/maison/schema.py", line 2, in <module>
    from pydantic import BaseModel
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pydantic/__init__.cpython-310-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pydantic/__init__.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pydantic/__init__.cpython-310-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pydantic/__init__.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by lyz-code** [comment]
Hi @yoland68, thanks for taking the time to open an issue. I'm afraid I won't be able to help you on this one, I don't use mac nor ARM so I have no idea on how to fix it. 

It looks though that the problem comes from the pydantic library, I feel you should open the issue in their repository.

Good luck :)
